# Generated by Django 2.2.12 on 2021-02-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userType',
            field=models.CharField(choices=[('Public', 'Public'), ('Doctor', 'Doctor'), ('Admin', 'Admin')], default='Public', max_length=10),
        ),
    ]
