# Generated by Django 2.2.12 on 2021-02-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0003_auto_20210211_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='specialist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
