# Generated by Django 2.2.12 on 2021-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0004_userprofile_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
