# Generated by Django 2.2.12 on 2021-02-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0005_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('doctorId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40, null=True)),
                ('department', models.CharField(max_length=40, null=True)),
                ('doctorName', models.CharField(max_length=40, null=True)),
                ('appointmentDate', models.DateField()),
                ('appointmentTime', models.TimeField()),
                ('msg', models.TextField(max_length=500)),
                ('patientEmail', models.EmailField(max_length=100)),
                ('patientMobile', models.IntegerField()),
            ],
        ),
    ]
