# Generated by Django 2.2.12 on 2021-02-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0006_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PublicApp.UserProfile'),
            preserve_default=False,
        ),
    ]
