# Generated by Django 2.2.12 on 2021-02-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0007_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointmentId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
