# Generated by Django 2.2.12 on 2021-02-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0008_appointment_appointmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientAge',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
