# Generated by Django 2.2.12 on 2021-02-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0009_appointment_patientage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientId',
        ),
    ]
