# Generated by Django 2.2.12 on 2021-02-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0010_auto_20210224_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentId', models.PositiveIntegerField(null=True)),
                ('departmentName', models.CharField(max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PublicApp.UserProfile')),
            ],
        ),
    ]
