# Generated by Django 2.2.12 on 2021-02-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0014_auto_20210227_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
