# Generated by Django 2.2.12 on 2021-02-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0015_remove_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
