# Generated by Django 2.2.12 on 2021-02-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0017_department_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentId',
        ),
    ]
