# Generated by Django 2.2.12 on 2021-02-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0018_remove_appointment_appointmentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='departmentId',
        ),
    ]
