# Generated by Django 2.2.12 on 2021-03-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicApp', '0019_remove_department_departmentid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=40, null=True)),
                ('CustomerEmail', models.EmailField(max_length=100)),
                ('Subject', models.TextField(max_length=100)),
                ('msg', models.TextField(max_length=500)),
            ],
        ),
    ]
